#!/usr/bin/env python
import ssl
from http import server

class MyHTTPRequestHandler(server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_my_headers()

        server.SimpleHTTPRequestHandler.end_headers(self)

    def send_my_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cross-Origin-Opener-Policy", "same-origin")
        self.send_header("Cross-Origin-Embedder-Policy", "require-corp")

    def do_GET(self):
        # cut off a query string
        if '/dist/' not in self.path:
            self.path = "scripts/emscripten-dev" + self.path
        server.SimpleHTTPRequestHandler.do_GET(self)


if __name__ == '__main__':
    httpd = server.HTTPServer(('0.0.0.0', 4443), MyHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket (httpd.socket, certfile='./scripts/emscripten-dev/server/server.pem', server_side=True)
    httpd.serve_forever()
